### ISSUE TITLE
Refreshing page throws 404 Not Found

### ISSUE THREAD

**Issue by kjprovencal** [david-fisher/320-S21-Track2#143]

**Comment by judgerussell** [comment]
me and kyle broke it :P 

(we put the two front ends on different subdirectories, causing this to break. i'm not sure why. we will look into it)

**Comment by judgerussell** [comment]
oh it actually works on the scenario editor, but not the simulator. the fix is to change the Router component in Nav.js to have an attribute called basename, like this

<Router basename="/simulator">

**Comment by judgerussell** [comment]
donnnnnnnnnnne
