### ISSUE TITLE
Endpoint for getting stakeholders of a scenario

### ISSUE THREAD

**Issue by ahmedjaafar6** [david-fisher/320-S21-Track2#37]

**Comment by ahmedjaafar6** [comment]
This isn't done, we're going to do this at a later sprint.

**Comment by david-fisher** [comment]
If it isn't done, leave it open, move it back to TO-DO as part of the back log. Closing an issue entails the issue is completed.

**Comment by ahmedjaafar6** [comment]
Reopened to add the coverage matrix to the output of the endpoint

**Comment by ahmedjaafar6** [comment]
Coverage Matrix added to the output of the GET stakeholders endpoint
