### ISSUE TITLE
PUT & POST Reflections Endpoints

### ISSUE THREAD

**Issue by ahmedjaafar6** [david-fisher/320-S21-Track2#45]

**Comment by ahmedjaafar6** [comment]
This was a mistake. We thought the frontend wanted us to do this but it turns out it's not for us. So I'm closing it.

**Comment by ahmedjaafar6** [comment]
We made this issue by mistake because we misunderstood what endpoints we needed to make earlier in the semester, so since we can't delete issues, we're just going to repurpose it and rename it later when have something else to do instead of opening a new issue.

**Comment by ahmedjaafar6** [comment]
We have something to repurpose it with now so I renamed it and assigned someone to it.

**Comment by calvinchai** [comment]
completed without debugging since django crushed

**Comment by ahmedjaafar6** [comment]
Implemented last week but did not get tested due to Calvin's local DB having issues so it turned out to be broken, so it will be tested and fixed this sprint.

**Comment by calvinchai** [comment]
done
