### ISSUE TITLE
Combine Track 2 User Stories, Acceptance Tests, and Non-Functional Requirements into One Document/Wiki

### ISSUE THREAD

**Issue by erotondo** [david-fisher/320-S21-Track2#64]
We need to combine all user stories, acceptance tests, and non-functional requirement specs written by the individual teams into one document that then gets posted to a wiki page. Since Professor Fisher stated this is more or less a frontend task (since we have the majority of the stories and tests), I have asked my team's secretary, @connor-humbert, to create this document. Other individuals are welcome to help Connor, and if he hasn't reached out to your team already, please send him your user stories and acceptance tests. Thank you!

**Comment by jdrecoulle0001** [comment]
Assigned Doge Secretary to assist with task

**Comment by ahmedjaafar6** [comment]
(segfaulters team) @zetangL (secretary) can you please provide them ours? thanks
 EDIT: It turns out Zetang already sent it last night.
