### ISSUE TITLE
Clone 320-F20-Track-III Repo into this Repo

### ISSUE THREAD

**Issue by Enoch-Hsiao** [david-fisher/320-S21-Track2#7]
Assign a member or members to clone the [320-F20-Track-III repo](https://github.com/david-fisher/320-F20-Track-III) into this repo.

**Comment by judgerussell** [comment]
we cloned the files in with the previous repo's history. it's all in the "master" branch which is not currently the default. could you (or someone who has access) switch the default branch to "master"?

**Comment by Enoch-Hsiao** [comment]
> 
> 
> we cloned the files in with the previous repo's history. it's all in the "master" branch which is not currently the default. could you (or someone who has access) switch the default branch to "master"?

~~Post a pull request with your changes. I don't think it has anything to do with permissions.~~

I would try sending a pull request into the main branch. This might help.

https://stackoverflow.com/questions/23344320/there-isnt-anything-to-compare-nothing-to-compare-branches-are-entirely-diffe

Fisher could probably change the default branch but I think it's better to go through the process of pull-request -> review -> merge especially for a less involved assignment like this.

**Comment by judgerussell** [comment]
thanks Enoch! trying it right now. I wanted to preserve the commit history of the old repo, but maybe it caused more trouble than it was worth :p
