### ISSUE TITLE
Create a team Wiki Page

### ISSUE THREAD

**Issue by marcinknara** [david-fisher/320-S21-Track2#8]
Create a team project page under "Projects" and then ceate a team wiki page under the "Wiki" tab that contains the name of your team, your teammates, the PM, and your roles.

**Comment by gzhihongwei** [comment]
[URL to team project page](https://github.com/david-fisher/320-S21-Track2/projects/3)
[Url to Cerberus Team Wiki](https://github.com/david-fisher/320-S21-Track2/wiki/Cerberus-Team-Wiki)
