### ISSUE TITLE
Fix Fatal Error: too many connections

### ISSUE THREAD

**Issue by StephenMoynahanIV** [david-fisher/320-S21-Track2#95]
django.db.utils.OperationalError: FATAL:  too many connections for role "cnehcbso"
Extremely detrimental bug. Check with database team. 
Fixed by database team merging local database functionality.

**Comment by Enoch-Hsiao** [comment]
This is because of elephantSQL having a limit of 5 users online at one time. Will be fixed once we switch to CSCF database.
